-- Consolidate clinical data in PostgreSQL.
BEGIN;

CREATE TABLE IF NOT EXISTS prescriptions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id  BIGINT NOT NULL,
    patient_name    VARCHAR(100) NOT NULL,
    medication      VARCHAR(100) NOT NULL,
    doctor_notes    VARCHAR(200),
    pharmacy_name   VARCHAR(255),
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_prescriptions_appointment FOREIGN KEY (appointment_id)
        REFERENCES appointments(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_prescriptions_appointment
    ON prescriptions(appointment_id);

CREATE TABLE IF NOT EXISTS medical_reports (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id  BIGINT NOT NULL,
    prescription_id BIGINT,
    title           VARCHAR(150) NOT NULL,
    report_type     VARCHAR(80) NOT NULL,
    report_date     TIMESTAMP NOT NULL,
    notes           VARCHAR(2000),
    file_url        VARCHAR(2048),
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_reports_appointment FOREIGN KEY (appointment_id)
        REFERENCES appointments(id) ON DELETE CASCADE,
    CONSTRAINT fk_reports_prescription FOREIGN KEY (prescription_id)
        REFERENCES prescriptions(id) ON DELETE SET NULL,
    CONSTRAINT ck_reports_file_url CHECK (
        file_url IS NULL OR file_url ~ '^https://.+'
    )
);

CREATE INDEX IF NOT EXISTS idx_medical_reports_appointment
    ON medical_reports(appointment_id, report_date DESC);

COMMIT;
