spring.application.name=smartcare
server.port=8080
spring.devtools.restart.enabled=false
spring.web.resources.static-locations=classpath:/static/
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

# DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/smartcare}
spring.datasource.username=${DB_USERNAME:smartcare}
spring.datasource.password=${DB_PASSWORD:smartcare}

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:validate}
spring.jpa.open-in-view=false

spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/smartcare}
spring.data.mongodb.auto-index-creation=true

api.path=/api/

jwt.secret-key=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS:604800000}

app.bootstrap-admin.username=${ADMIN_USERNAME}
app.bootstrap-admin.password=${ADMIN_PASSWORD}
