-- SmartCare PostgreSQL schema
-- Run after create_database.sql:
--   psql -U smartcare -d smartcare -f database/schema.sql

BEGIN;

CREATE TABLE IF NOT EXISTS admins (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR(100) NOT NULL UNIQUE,
    password    VARCHAR(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS doctors (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    specialty   VARCHAR(50) NOT NULL,
    email       VARCHAR(254) NOT NULL UNIQUE,
    password    VARCHAR(60) NOT NULL,
    phone       VARCHAR(10) UNIQUE,
    rating      INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT ck_doctors_rating CHECK (rating BETWEEN 0 AND 5),
    CONSTRAINT ck_doctors_phone CHECK (phone IS NULL OR phone ~ '^[0-9]{10}$')
);

CREATE TABLE IF NOT EXISTS patients (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    email       VARCHAR(254) NOT NULL UNIQUE,
    password    VARCHAR(60) NOT NULL,
    phone       VARCHAR(10) NOT NULL UNIQUE,
    address     VARCHAR(255) NOT NULL,
    birthdate   TIMESTAMP NOT NULL,
    alias       VARCHAR(255),
    CONSTRAINT ck_patients_phone CHECK (phone ~ '^[0-9]{10}$')
);

CREATE TABLE IF NOT EXISTS doctor_available_times (
    doctor_id   BIGINT NOT NULL,
    time_slot   VARCHAR(5) NOT NULL,
    CONSTRAINT pk_doctor_available_times PRIMARY KEY (doctor_id, time_slot),
    CONSTRAINT fk_available_times_doctor FOREIGN KEY (doctor_id)
        REFERENCES doctors(id) ON DELETE CASCADE,
    CONSTRAINT ck_available_time_format CHECK (
        time_slot ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$'
    )
);

CREATE TABLE IF NOT EXISTS appointments (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_id           BIGINT NOT NULL,
    patient_id          BIGINT NOT NULL,
    appointment_time    TIMESTAMP NOT NULL,
    status              INTEGER NOT NULL DEFAULT 0,
    notes               VARCHAR(1000),
    CONSTRAINT fk_appointments_doctor FOREIGN KEY (doctor_id)
        REFERENCES doctors(id) ON DELETE CASCADE,
    CONSTRAINT fk_appointments_patient FOREIGN KEY (patient_id)
        REFERENCES patients(id) ON DELETE CASCADE,
    CONSTRAINT uk_appointment_doctor_time UNIQUE (doctor_id, appointment_time),
    CONSTRAINT ck_appointments_status CHECK (status IN (0, 1))
);

CREATE TABLE IF NOT EXISTS prescriptions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id      BIGINT NOT NULL,
    patient_name        VARCHAR(100) NOT NULL,
    medication          VARCHAR(100) NOT NULL,
    doctor_notes        VARCHAR(200),
    pharmacy_name       VARCHAR(255),
    CONSTRAINT fk_prescriptions_appointment FOREIGN KEY (appointment_id)
        REFERENCES appointments(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_appointments_patient_time
    ON appointments(patient_id, appointment_time);

CREATE INDEX IF NOT EXISTS idx_appointments_doctor_time
    ON appointments(doctor_id, appointment_time);

CREATE INDEX IF NOT EXISTS idx_prescriptions_appointment
    ON prescriptions(appointment_id);

COMMIT;
